# Generated by Django 5.0.3 on 2024-04-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='timestamp',
        ),
    ]
