# Generated by Django 5.0.1 on 2024-03-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_creation_time_listing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.CharField(max_length=1000),
        ),
    ]
