# Generated by Django 5.0.1 on 2024-03-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_price',
            new_name='price',
        ),
    ]
